version: 0.0
os: linux
files:
  - source: target/
    destination: /usr/share/tomcat7/webapps
permissions:
  - object: /usr/share/tomcat7/webapps
    pattern: "**"
    owner: root
    group: tomcat
    mode: 755
    type:
      - file
hooks:
  BeforeInstall:
   - location: scripts/stoptomcat.sh
     runas: root
  AfterInstall:
   - location: scripts/starttomcat.sh
     runas: root
